# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c402f2859c91d8e51819fd5f0d13e19e2051602b0e78b44fed26d007b5494bdb20f758d4aaefcd7264b759aaed1b8bca4ddc0f44269c7ae6ddcf5a2a43f9463

test:
  secret_key_base: 58798ae12d8a0acdde7ac705d0d4a31d593c1e51df4c5ddc0cbfcc077b1cab42caf686d691f334eb53d975c096005aa212e143eae6dc245b894696350c898f38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
